/* AUTOGENERATED / DYNAMIC SUPABASE CONFIGURATION */

export const projectId =
  (import.meta.env.VITE_SUPABASE_PROJECT_ID as string) || "gaxrwsyjhqhyfxokpjjq";

export const publicAnonKey =
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string) ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdheHJ3c3lqaHFoeWZ4b2twampxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMzMDAyMzMsImV4cCI6MjA5ODg3NjIzM30.Yu5KDBCNifFwdNJOBjTV7f34yuF8KaMk_5SNKLtGP-E";